name: Bug report
description: Report errors or unexpected behavior
labels: bug
body:
  - type: checkboxes
    attributes:
      label: Is there already an issue for your problem?
      description: Please make sure you are not creating an already submitted issue. Check closed issues as well.
      options:
        - label: I have checked older issues, open and closed
          required: true

  - type: checkboxes
    attributes:
      label: Are you using the latest version of the package?
      description: Please make sure you are using the latest version of the package. If you are not, please update and check if the issue still persists.
      options:
        - label: I am using the latest version
          required: true

  - type: input
    attributes:
      label: Where are you running the package?
      description: Please provide the information about the rutime you are using.
      placeholder: Node.js v20.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a code snippet that can reproduce it.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the expected behavior?

  - type: textarea
    attributes:
      label: What do you see instead?

  - type: textarea
    attributes:
      label: Additional information
      description: Any other additional information that may help.
